
package team.t.course.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyServiceImplService", targetNamespace = "pers.liam.countManager.MyService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyServiceImplService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddUserResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/addUserRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/addUserResponse")
    public int addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "modify_userInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modify_userInfo", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.ModifyUserInfo")
    @ResponseWrapper(localName = "modify_userInfoResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.ModifyUserInfoResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/modify_userInfoRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/modify_userInfoResponse")
    public boolean modifyUserInfo();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "get_userInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get_userInfo", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetUserInfo")
    @ResponseWrapper(localName = "get_userInfoResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetUserInfoResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/get_userInfoRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/get_userInfoResponse")
    public String getUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "verify_userInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify_userInfo", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.VerifyUserInfo")
    @ResponseWrapper(localName = "verify_userInfoResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.VerifyUserInfoResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/verify_userInfoRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/verify_userInfoResponse")
    public int verifyUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
