
package team.t.course.web;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyServiceImplService", targetNamespace = "pers.liam.countManager.MyService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyServiceImplService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddUserResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/addUserRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/addUserResponse")
    public int addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserInfo", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.ModifyUserInfo")
    @ResponseWrapper(localName = "modifyUserInfoResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.ModifyUserInfoResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/modifyUserInfoRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/modifyUserInfoResponse")
    public boolean modifyUserInfo();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNickname", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetNickname")
    @ResponseWrapper(localName = "getNicknameResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetNicknameResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/getNicknameRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/getNicknameResponse")
    public String getNickname(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeUserInfo", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.ChangeUserInfo")
    @ResponseWrapper(localName = "changeUserInfoResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.ChangeUserInfoResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/changeUserInfoRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/changeUserInfoResponse")
    public int changeUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyUserInfo", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.VerifyUserInfo")
    @ResponseWrapper(localName = "verifyUserInfoResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.VerifyUserInfoResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/verifyUserInfoRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/verifyUserInfoResponse")
    public int verifyUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setIP", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.SetIP")
    @ResponseWrapper(localName = "setIPResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.SetIPResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/setIPRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/setIPResponse")
    public int setIP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIP", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetIP")
    @ResponseWrapper(localName = "getIPResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetIPResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/getIPRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/getIPResponse")
    public String getIP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<team.t.course.web.Friend>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFriendList", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetFriendList")
    @ResponseWrapper(localName = "getFriendListResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.GetFriendListResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/getFriendListRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/getFriendListResponse")
    public List<Friend> getFriendList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFriend", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.SearchFriend")
    @ResponseWrapper(localName = "searchFriendResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.SearchFriendResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/searchFriendRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/searchFriendResponse")
    public List<String> searchFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFriendMsg", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddFriendMsg")
    @ResponseWrapper(localName = "addFriendMsgResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddFriendMsgResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/addFriendMsgRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/addFriendMsgResponse")
    public int addFriendMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delFriend", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.DelFriend")
    @ResponseWrapper(localName = "delFriendResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.DelFriendResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/delFriendRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/delFriendResponse")
    public int delFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkFriend", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.CheckFriend")
    @ResponseWrapper(localName = "checkFriendResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.CheckFriendResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/checkFriendRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/checkFriendResponse")
    public List<String> checkFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFriend", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddFriend")
    @ResponseWrapper(localName = "addFriendResponse", targetNamespace = "pers.liam.countManager.MyService", className = "team.t.course.web.AddFriendResponse")
    @Action(input = "pers.liam.countManager.MyService/MyServiceImplService/addFriendRequest", output = "pers.liam.countManager.MyService/MyServiceImplService/addFriendResponse")
    public int addFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

}
